In [ ]:
import torch
from torch import nn

In [ ]:
# x = torch.tensor([1,])
# model = nn.Linear(1,1)

# print(model.weight)
# print(model.bias)

# y = model(x)
# print(y)

Parameter containing:
tensor([[-0.3019]], requires_grad=True)
Parameter containing:
tensor([0.4842], requires_grad=True)


RuntimeError: mat1 and mat2 must have the same dtype, but got Long and Float

In [ ]:
import torch
from torch import nn

x = torch.tensor([1.], dtype=torch.float32) # Changed the type of the tensor to float32
model = nn.Linear(1,1)

print(model.weight)
print(model.bias)

y = model(x)
print(y)

y = x @ model.weight + model.bias
print(y)

Parameter containing:
tensor([[0.4479]], requires_grad=True)
Parameter containing:
tensor([-0.8578], requires_grad=True)
tensor([-0.4099], grad_fn=<ViewBackward0>)
tensor([-0.4099], grad_fn=<AddBackward0>)


In [ ]:
fc1 = nn.Linear(1,3) # fully_connected
fc2 = nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

Parameter containing:
tensor([[ 0.5337],
        [-0.4234],
        [-0.3975]], requires_grad=True)
Parameter containing:
tensor([ 0.8741, -0.2631, -0.9827], requires_grad=True)
Parameter containing:
tensor([[ 0.1030,  0.4672, -0.3231]], requires_grad=True)
Parameter containing:
tensor([-0.2472], requires_grad=True)


In [ ]:
print(fc2(fc1(x)))

tensor([0.0230], grad_fn=<ViewBackward0>)


In [ ]:
x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

tensor([ 1.4078, -0.6865, -1.3802], grad_fn=<ViewBackward0>)
tensor([0.0230], grad_fn=<ViewBackward0>)


In [ ]:
y = (x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias


In [ ]:
model = nn.Sequential(fc1, fc2) # layer 풀칠
# nn.Linear 는 개x채x행x열에서 "채" 형태로 (1D data) 들어오길 기대하는 녀석이다.
# 즉, 노드 하나가 곧 한 채널의 의미한다.
# 따라서, 데이터 여러개를 통과시키고 싶다면 개x채 의 형태로 줘야 함
# why T? weight도 개x채 형태로 만들기 위함!
# 일단, weight shape 개x채에서 채는 무조건 앞에 거 채널 개수와 맞추셈!
# 예를 들면 nn.Linear(2,3)
# 두 채널 값을 가지고 3x2 행렬을 만드는 것


In [ ]:
fc1 = nn.Linear(1,3)
fc2 = nn.Linear(3,1)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

model = nn.Sequential(fc1, fc2) # layer 풀칠
x=torch.tensor([1.])
print(model(x))

tensor([-1.2947,  0.4005, -1.0174], grad_fn=<ViewBackward0>)
tensor([-1.1130], grad_fn=<ViewBackward0>)
tensor([-1.1130], grad_fn=<ViewBackward0>)


In [ ]:
model = nn.Sequential(nn.Linear(2,5),
                      nn.Linear(5,10),
                      nn.Linear(10,3))

x = torch.randn(2)
print(x)
print(model(x))

x = torch.randn(1,2)
print(x)
print(model(x))

x = torch.randn(5,2) # 개x채 => 두 개의 채널 값(키, 몸무게)을 가지는 데이터(사람) 5개를 통과시킴
print(x)
print(model(x))

x = torch.randn(2,3,1,4,5,2)
print(model(x).shape)
print(model(x))

tensor([0.8427, 0.2839])
tensor([ 0.4684, -0.1107,  0.2032], grad_fn=<ViewBackward0>)
tensor([[ 0.9210, -1.5977]])
tensor([[0.0956, 0.3071, 0.0486]], grad_fn=<AddmmBackward0>)
tensor([[-1.2832e+00, -1.8611e-04],
        [-7.1820e-01, -5.3828e-01],
        [-9.4983e-01,  9.1838e-01],
        [ 4.5923e-02, -5.4395e-01],
        [-1.9974e+00, -2.6819e-01]])
tensor([[ 0.8112, -0.4720,  0.0501],
        [ 0.6033, -0.2448,  0.0389],
        [ 0.9238, -0.6022,  0.1482],
        [ 0.4595, -0.0919,  0.0848],
        [ 0.8935, -0.5565, -0.0159]], grad_fn=<AddmmBackward0>)
torch.Size([2, 3, 1, 4, 5, 3])
tensor([[[[[[ 7.9196e-01, -4.6285e-01,  2.0237e-01],
            [ 4.9571e-01, -1.3894e-01,  1.8412e-01],
            [ 6.3979e-01, -2.7690e-01, -6.0344e-02],
            [ 5.8638e-01, -2.2254e-01, -1.1441e-02],
            [ 5.0219e-01, -1.4827e-01,  2.1339e-01]],

           [[ 5.1490e-01, -1.4193e-01, -4.7636e-02],
            [ 4.7109e-01, -9.6544e-02, -1.7775e-02],
            [ 5.3999e-01, -

In [ ]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(2, 5)
        self.fc2 = nn.Linear(5, 10)
        self.fc3 = nn.Linear(10, 3)
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.sig1(x)
        x = self.fc2(x)
        x = self.sig2(x)
        x = self.fc3(x)
        x = self.sig3(x)
        return x

model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)

tensor([[[0.4564, 0.5731, 0.4785],
         [0.4603, 0.5744, 0.4716],
         [0.4595, 0.5712, 0.4732],
         [0.4564, 0.5712, 0.4789],
         [0.4593, 0.5722, 0.4738]],

        [[0.4595, 0.5722, 0.4733],
         [0.4574, 0.5720, 0.4773],
         [0.4583, 0.5742, 0.4754],
         [0.4621, 0.5746, 0.4673],
         [0.4559, 0.5733, 0.4789]]], grad_fn=<SigmoidBackward0>)


In [ ]:
print(model)

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)


In [ ]:
class MyModel2(nn.Module):
    def __init__(self):
        super().__init__()

        self.Linear = nn.Sequential(
        nn.Linear(2, 5),
        nn.Sigmoid(),
        nn.Linear(5, 10),
        nn.Sigmoid(),
        nn.Linear(10, 3),
        nn.Sigmoid())

    def forward(self, x):
        x = self.Linear(x)
        return x

model2 = MyModel2()
x = torch.randn(5,2)
y = model(x)
print(y)

tensor([[0.4963, 0.3948, 0.5813],
        [0.4945, 0.4005, 0.5815],
        [0.4953, 0.4000, 0.5810],
        [0.4961, 0.3919, 0.5822],
        [0.4972, 0.3941, 0.5806]], grad_fn=<SigmoidBackward0>)


In [ ]:
print(model2)
print(model2.Linear[0].weight) # Changed model2.linear to model2.Linear
print(model2.Linear[2].weight)

MyModel2(
  (Linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)
Parameter containing:
tensor([[-0.2379,  0.1382],
        [ 0.4098,  0.4831],
        [-0.3914, -0.5309],
        [ 0.3696, -0.6343],
        [ 0.2328, -0.1720]], requires_grad=True)
Parameter containing:
tensor([[ 0.4387,  0.3209, -0.0616,  0.1493,  0.0224],
        [ 0.0137,  0.0289,  0.3020, -0.1678,  0.4375],
        [-0.1399,  0.3113, -0.0244,  0.4124,  0.2193],
        [-0.2623,  0.2744,  0.0839,  0.1042,  0.0991],
        [-0.2210, -0.0452,  0.3158, -0.0827,  0.2366],
        [ 0.1184,  0.3254, -0.2769, -0.4382, -0.0543],
        [ 0.3220, -0.4170, -0.2935, -0.0714,  0.1373],
        [ 0.2927,  0.2617, -0.1828, -0.0158, -0.4125],
        [-0.0784,  0.2187,  0.3485,  0.0446, -0.3766],
        [-0.2536,  0.2405, 

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3980,  0.6362],
         [ 0.3623, -0.4896],
         [ 0.5912,  0.2456],
         [ 0.7037, -0.2521],
         [ 0.6883,  0.3070]], requires_grad=True),
 Parameter containing:
 tensor([-0.5189, -0.6636,  0.1321,  0.5189, -0.0417], requires_grad=True),
 Parameter containing:
 tensor([[ 0.0135,  0.0479,  0.3257,  0.0403,  0.2012],
         [ 0.2035, -0.3324, -0.4004, -0.3103, -0.2207],
         [ 0.1305, -0.1503, -0.1710,  0.2792,  0.2869],
         [ 0.3532,  0.4307, -0.0961, -0.0043,  0.1860],
         [-0.1828,  0.3844,  0.1667, -0.2531, -0.4349],
         [-0.0120, -0.0377,  0.3462, -0.2693,  0.0951],
         [ 0.3326,  0.4104,  0.3932, -0.1266,  0.2379],
         [-0.4436, -0.0428, -0.2446, -0.3337,  0.4301],
         [ 0.0316, -0.1555,  0.3103, -0.1754, -0.4277],
         [ 0.3260, -0.1892, -0.2858,  0.3148,  0.1931]], requires_grad=True),
 Parameter containing:
 tensor([-0.3751,  0.1493,  0.4357, -0.0169, -0.1665,  0.0388,  0.2330, -0.2869,
  

In [ ]:
# 파라미터 수 구하기
num = sum([p.numel() for p in model.parameters() if p.requires_grad])
print(num)

108
